services:
  # Zinc App
  zinc_auth_container:
    build:
      context: .
      dockerfile: Dockerfile
    
    # named image
    image: nguyennt63/zinc_auth:latest
    # named container
    container_name: zinc_auth_container
    # ports of container
    ports:
      - "3000:3000"
    # select env
    # env_file:
    #   - zinc_app/envs/.env

    # command start container
    working_dir: /app/src
    entrypoint: ["make"]
    command: ["run-server"]

    # healthcheck
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:5000/health/"]
    #   interval: 15s
    #   timeout: 3s
    #   retries: 5

    # restart
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  zinc_auth_data: